# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7527d94ed1e7fe9fd53a0b6a29ba98be48a5c51a8e5c835562cf11bced2ed8f4ed9ec921dcac6b39f47f391a9e42c60ad482bfbd92b97998cb1c2741e44e47e0

test:
  secret_key_base: 44d8c05aee59fea5276fd8dcc7ff9257e09ff1343285930ded99b07d9a1d33f8d74d07f2ee6fdc6a53cc198131deeb54daddda7b126d1b582305a9c15b90793c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
